services:
  database:
    build:
      context: ./WebApplication1/Dockerfile-sql
    image: mssql
    
    ports:
      - "1433:1433"
   
  web:
    build:
      context: "./WebApplication1"
      dockerfile: "/Dockerfile-mvc/Dockerfile"
    image: "mvc"
    ports:
      - "8080:80"
    depends_on:
      - database